var artcle={
    article_publish:function(fd,callback){
        $.ajax({
            url:APIURL.article_publish,
            type:'post',
            data:fd,
            contentType:false,
            processData:false,
            success:function(res){
                callback(res)
            }
        })
    },
    article_get:function(data,callback){
        $.ajax(
            {
                url:APIURL.article_get,
                type:'get',
                data:data,
                success:function(res){
                    callback(res)
                }
            }

        )
    },
    article_del:function(id,callback){
        $.get(APIURL.article_del,{id:id},function(res){
            callback(res)
        })
    },
    article_edit:function(fd,callback){
        $.ajax({
            url:APIURL.article_edit,
            type:'post',
            data:fd,
            contentType:false,
            processData:false,
            success:function(res){
                callback(res)
            }
        })
    }
}